# Home Assistant Secrets
# Add your Xiaomi device credentials here

# Xiaomi IR Remote (L05G) - Your device IP
xiaomi_ir_host: "192.168.68.68"  # Correct device IP
xiaomi_ir_token: "00000000000000000000000000000000"  # Placeholder token for testing

# Add other secrets as needed
# example_secret: "your_secret_value"
