# Home Assistant Lovelace Configuration - Production Solution
views:
  - title: Overview
    icon: mdi:home
    path: overview
    badges: []
    cards:
      - type: markdown
        content: |
          # 🏠 Home Assistant Overview
          Welcome to your Home Assistant dashboard!
          
          **Xiaomi TV Controls**: Go to the "Remote Control" tab to control your Hisense TV.

  - title: Remote Control
    icon: mdi:remote
    path: remote-control
    badges: []
    cards:
      - type: markdown
        content: |
          # 🎮 Xiaomi IR Remote Control
          **Device**: `192.168.68.68` | **Status**: `Connected` | **Protocol**: `UDP IR`
        card_mod:
          style: |
            ha-card {
              background: var(--card-background-color);
              border-radius: var(--ha-card-border-radius);
              box-shadow: var(--ha-card-box-shadow);
              padding: 16px;
              text-align: center;
              margin-bottom: 16px;
            }
            h1 {
              color: var(--primary-color);
              font-size: 24px;
              margin-bottom: 10px;
            }
            p {
              color: var(--secondary-text-color);
              font-size: 14px;
            }
            strong {
              color: var(--text-color);
            }

      - type: horizontal-stack
        cards:
          - type: button
            name: TV Power
            icon: mdi:power
            tap_action:
              action: call-service
              service: script.xiaomi_ir_power
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Volume Up
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: script.xiaomi_ir_volume_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Volume Down
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: script.xiaomi_ir_volume_down
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Mute
            icon: mdi:volume-mute
            tap_action:
              action: call-service
              service: script.xiaomi_ir_mute
            show_state: false
            show_name: true
            show_icon: true

      - type: horizontal-stack
        cards:
          - type: button
            name: Channel Up
            icon: mdi:chevron-up
            tap_action:
              action: call-service
              service: script.xiaomi_ir_channel_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Channel Down
            icon: mdi:chevron-down
            tap_action:
              action: call-service
              service: script.xiaomi_ir_channel_down
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Input
            icon: mdi:hdmi-port
            tap_action:
              action: call-service
              service: script.xiaomi_ir_input
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Menu
            icon: mdi:menu
            tap_action:
              action: call-service
              service: script.xiaomi_ir_menu
            show_state: false
            show_name: true
            show_icon: true

      - type: horizontal-stack
        cards:
          - type: button
            name: Back
            icon: mdi:arrow-left
            tap_action:
              action: call-service
              service: script.xiaomi_ir_back
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: OK
            icon: mdi:check
            tap_action:
              action: call-service
              service: script.xiaomi_ir_ok
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Up
            icon: mdi:arrow-up
            tap_action:
              action: call-service
              service: script.xiaomi_ir_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Down
            icon: mdi:arrow-down
            tap_action:
              action: call-service
              service: script.xiaomi_ir_down
            show_state: false
            show_name: true
            show_icon: true

      - type: horizontal-stack
        cards:
          - type: button
            name: Left
            icon: mdi:arrow-left
            tap_action:
              action: call-service
              service: script.xiaomi_ir_left
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Right
            icon: mdi:arrow-right
            tap_action:
              action: call-service
              service: script.xiaomi_ir_right
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Test All
            icon: mdi:test-tube
            tap_action:
              action: call-service
              service: script.xiaomi_ir_test_all
            show_state: false
            show_name: true
            show_icon: true

      - type: entities
        title: Device Status
        entities:
          - sensor.xiaomi_ir_device_status
          - sensor.xiaomi_ir_last_command
          - sensor.xiaomi_ir_commands_sent