# Home Assistant Lovelace Configuration - Proper Overview
views:
  - title: Overview
    icon: mdi:home
    path: overview
    badges: []
    cards:
      - type: markdown
        content: |
          # 🏠 Home Assistant Overview
          Welcome to your Home Assistant dashboard!
          
          This is your main overview where you can see all your devices and entities.

      - type: entities
        title: System Information
        entities:
          - sun.sun
          - sensor.date
          - sensor.time
          - sensor.uptime

      - type: entities
        title: Weather
        entities:
          - weather.home

      - type: entities
        title: Energy
        entities:
          - sensor.energy_consumption
          - sensor.energy_production

      - type: entities
        title: Security
        entities:
          - alarm_control_panel.home
          - binary_sensor.door_sensor
          - binary_sensor.motion_sensor

      - type: entities
        title: Lights
        entities:
          - light.living_room
          - light.bedroom
          - light.kitchen

      - type: entities
        title: Climate
        entities:
          - climate.thermostat
          - sensor.temperature
          - sensor.humidity

      - type: entities
        title: Media
        entities:
          - media_player.living_room_tv
          - media_player.bedroom_speaker

      - type: entities
        title: Xiaomi IR Remote Control
        entities:
          - sensor.xiaomi_ir_device_status
          - sensor.xiaomi_ir_last_command
          - sensor.xiaomi_ir_commands_sent

      - type: horizontal-stack
        cards:
          - type: button
            name: TV Power
            icon: mdi:power
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_power
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Volume Up
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_volume_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Volume Down
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_volume_down
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Mute
            icon: mdi:volume-mute
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_mute
            show_state: false
            show_name: true
            show_icon: true

      - type: markdown
        content: |
          ## 🎮 Quick TV Controls
          Use the buttons above for quick TV control, or go to the "Remote Control" tab for full control.

  - title: Remote Control
    icon: mdi:remote
    path: remote-control
    badges: []
    cards:
      - type: markdown
        content: |
          # 🎮 Xiaomi IR Remote Control
          **Device**: `192.168.68.62` | **Status**: `Connected` | **Protocol**: `IR Commands`

      - type: horizontal-stack
        cards:
          - type: button
            name: TV Power
            icon: mdi:power
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_power
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Volume Up
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_volume_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Volume Down
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_volume_down
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Mute
            icon: mdi:volume-mute
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_mute
            show_state: false
            show_name: true
            show_icon: true

      - type: horizontal-stack
        cards:
          - type: button
            name: Channel Up
            icon: mdi:chevron-up
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_channel_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Channel Down
            icon: mdi:chevron-down
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_channel_down
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Input
            icon: mdi:hdmi-port
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_input
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Menu
            icon: mdi:menu
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_menu
            show_state: false
            show_name: true
            show_icon: true

      - type: horizontal-stack
        cards:
          - type: button
            name: Back
            icon: mdi:arrow-left
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_back
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: OK
            icon: mdi:check
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_ok
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Up
            icon: mdi:arrow-up
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_up
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Down
            icon: mdi:arrow-down
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_down
            show_state: false
            show_name: true
            show_icon: true

      - type: horizontal-stack
        cards:
          - type: button
            name: Left
            icon: mdi:arrow-left
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_left
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Right
            icon: mdi:arrow-right
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_right
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Test All
            icon: mdi:test-tube
            tap_action:
              action: call-service
              service: shell_command.xiaomi_ir_test_all
            show_state: false
            show_name: true
            show_icon: true

      - type: entities
        title: Device Status
        entities:
          - sensor.xiaomi_network_ping
          - sensor.xiaomi_network_latency

  - title: Network Monitor
    icon: mdi:network
    path: network-monitor
    badges: []
    cards:
      - type: markdown
        content: |
          # 🌐 Network Monitoring
          **Target Device**: `192.168.68.68` | **Network**: `SA` | **Monitoring**: `Active`

      - type: entities
        title: Network Status
        entities:
          - sensor.xiaomi_network_ping
          - sensor.xiaomi_network_latency
          - sensor.xiaomi_network_activity
          - sensor.xiaomi_connection_quality

      - type: entities
        title: Network Monitor Status
        entities:
          - sensor.network_monitor_status
          - sensor.xiaomi_command_detection
          - sensor.network_interfaces

      - type: horizontal-stack
        cards:
          - type: button
            name: Start Monitor
            icon: mdi:play
            tap_action:
              action: call-service
              service: script.start_network_monitoring
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Stop Monitor
            icon: mdi:stop
            tap_action:
              action: call-service
              service: script.stop_network_monitoring
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Check Status
            icon: mdi:refresh
            tap_action:
              action: call-service
              service: script.check_network_status
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Restart Monitor
            icon: mdi:restart
            tap_action:
              action: call-service
              service: script.restart_network_monitoring
            show_state: false
            show_name: true
            show_icon: true

      - type: entities
        title: Network Log
        entities:
          - sensor.network_monitor_log

      - type: entities
        title: Network State
        entities:
          - sensor.network_monitor_state

      - type: entities
        title: Network Traffic
        entities:
          - sensor.network_traffic_monitor

  - title: Xiaomi Analyzer
    icon: mdi:microscope
    path: xiaomi-analyzer
    badges: []
    cards:
      - type: markdown
        content: |
          # 🔬 Xiaomi Command Analyzer
          **Target Device**: `192.168.68.68` | **Analysis**: `Active` | **Purpose**: `Learn Commands`

      - type: entities
        title: Analysis Status
        entities:
          - sensor.xiaomi_analysis_status
          - sensor.xiaomi_device_type
          - sensor.xiaomi_open_ports

      - type: horizontal-stack
        cards:
          - type: button
            name: Analyze Device
            icon: mdi:search
            tap_action:
              action: call-service
              service: script.analyze_xiaomi_device
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Test Connection
            icon: mdi:network
            tap_action:
              action: call-service
              service: script.test_xiaomi_connection
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Check Analysis
            icon: mdi:refresh
            tap_action:
              action: call-service
              service: script.check_xiaomi_analysis
            show_state: false
            show_name: true
            show_icon: true

          - type: button
            name: Full Analysis
            icon: mdi:chart-line
            tap_action:
              action: call-service
              service: script.full_xiaomi_analysis
            show_state: false
            show_name: true
            show_icon: true

      - type: entities
        title: Analysis Log
        entities:
          - sensor.xiaomi_analysis_log

      - type: entities
        title: Discovered Commands
        entities:
          - sensor.xiaomi_commands

      - type: entities
        title: Protocol Information
        entities:
          - sensor.xiaomi_protocol

      - type: entities
        title: Port Scan Results
        entities:
          - sensor.xiaomi_port_scan